apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-blue
  labels:
    version: v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world-blue
        env: blue
    spec:
      containers:
      - name: hello-world 
        image: quay.io/praveenr/hello-world-bluegreen:v1
        ports:
        - name: web
          containerPort: 5000
        - name: metrics
          containerPort: 8000
