kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: bluegreen
  namespace: default
  annotations:
    kubernetes.io/ingress.class: tectonic
spec:
  rules:
    - host: bluegreen.se-cluster.se.k8s.work
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-world-blue
              servicePort: 5000
status:
  loadBalancer: {}
